version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  minesweeper-client:
    image: ${DOCKER_REGISTRY-}minesweeper-client
    restart: always
    build:
      context: presentation/web
      target: dev
    labels:
      - "traefik.http.routers.minesweeper.rule=Host(`web.minesweeper.localhost`)"
      - "traefik.http.services.minesweeper.loadbalancer.server.port=3000"
    environment:
      - CI=true
      - REACT_APP_API_URL=http://api.minesweeper.localhost

  minesweeper-ranking-api:
    image: ${DOCKER_REGISTRY-}minesweeper-ranking-api
    restart: always
    build:
      context: ranking
      target: prod
    labels:
      - "traefik.http.routers.rankingapi.rule=Host(`api.minesweeper.localhost`) && PathPrefix(`/api/v1/ranking`)"
      - "traefik.http.routers.rankingapi.middlewares=rankingapiratelimit"
      - "traefik.http.services.rankingapi.loadbalancer.server.port=80"      
      - "traefik.http.middlewares.rankingapiratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.rankingapiratelimit.ratelimit.burst=50"
    environment:
      - CONNECTIONSTRINGS__REDIS=redis
      - ALLOWEDHOSTS=api.minesweeper.localhost

  redis:
    image: redis:alpine3.18
    command: --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis_storage:/data

volumes:
  redis_storage:
    external: true