version: "3.9"
services:
  minesweeper-client:
    container_name: minesweeper-client
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - minesweeper-front-app:/app
      - minesweeper-front-app-packages:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true