version: "3.9"
services:
  minesweeper-client:
    image: rulyotano/minesweeper-presentation-web:0.0.15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.services.minesweeper.loadbalancer.server.port=80"
        - "traefik.http.routers.minesweeper.rule=Host(`minesweeper.rulyotano.com`)"
        - "traefik.http.routers.minesweeper.tls=true"
        - "traefik.http.routers.minesweeper.tls.certresolver=mycertresolver"
        - "traefik.http.routers.minesweeperhttp.rule=Host(`minesweeper.rulyotano.com`) || (Host(`api.minesweeper.rulyotano.com`) && Path(`/`))"
        - "traefik.http.routers.minesweeperhttp.middlewares=redirecthttps"
        - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirecthttps.redirectscheme.permanent=true"
    networks:
      - traefik

  minesweeper-ranking-api:
    image: rulyotano/minesweeper-ranking-api:0.0.3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.services.rankingapi.loadbalancer.server.port=80"
        - "traefik.http.routers.rankingapi.rule=Host(`api.minesweeper.rulyotano.com`) && PathPrefix(`/api/v1/ranking`)"
        - "traefik.http.routers.rankingapi.tls=true"
        - "traefik.http.routers.rankingapi.tls.certresolver=mycertresolver"
        - "traefik.http.routers.rankingapi.middlewares=rankingapiratelimit"
        - "traefik.http.routers.rankingapihttp.rule=Host(`api.minesweeper.rulyotano.com`) && PathPrefix(`/api/v1/ranking`)"
        - "traefik.http.routers.rankingapihttp.middlewares=redirecthttps,rankingapiratelimit"
        - "traefik.http.middlewares.rankingapiratelimit.ratelimit.average=100"
        - "traefik.http.middlewares.rankingapiratelimit.ratelimit.burst=50"
    environment:
      - CONNECTIONSTRINGS__REDIS=redis
      - ALLOWEDHOSTS=*
    networks:
      - traefik
      - backend

networks:
  traefik:
    external: true
  backend:
    external: true