version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.10
    environment:
      - TRAEFIK_API=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_SWARMMODE=true
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_CERTIFICATESRESOLVERS_MYCERTRESOLVER_ACME_HTTPCHALLENGE_ENTRYPOINT=web
      - TRAEFIK_CERTIFICATESRESOLVERS_MYCERTRESOLVER_ACME_EMAIL=contact@rulyotano.com
      - TRAEFIK_CERTIFICATESRESOLVERS_MYCERTRESOLVER_ACME_STORAGE=acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.minesweeper.rulyotano.com`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=rulyotano:$$2y$$05$$X8IeCe9aTKfQUFR6EMujqeASB22nQg1Ho.naDVh31yuz9xY2z4ux2"

  minesweeper-client:
    image: rulyotano/minesweeper-presentation-web:0.0.8
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.services.minesweeper.loadbalancer.server.port=80"
        - "traefik.http.routers.minesweeper.rule=Host(`minesweeper.rulyotano.com`)"
        - "traefik.http.routers.minesweeper.tls=true"
        - "traefik.http.routers.minesweeper.tls.certresolver=mycertresolver"
        - "traefik.http.routers.minesweeperhttp.rule=Host(`minesweeper.rulyotano.com`) || (Host(`api.minesweeper.rulyotano.com`) && Path(`/`))"
        - "traefik.http.routers.minesweeperhttp.middlewares=redirecthttps"
        - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirecthttps.redirectscheme.permanent=true"

  minesweeper-ranking-api:
    image: rulyotano/minesweeper-ranking-api:0.0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.services.rankingapi.loadbalancer.server.port=80"
        - "traefik.http.routers.rankingapi.rule=Host(`api.minesweeper.rulyotano.com`) && PathPrefix(`/api/v1/ranking`)"
        - "traefik.http.routers.rankingapi.tls=true"
        - "traefik.http.routers.rankingapi.tls.certresolver=mycertresolver"
        - "traefik.http.routers.rankingapi.middlewares=rankingapiratelimit"
        - "traefik.http.routers.rankingapihttp.rule=Host(`api.minesweeper.rulyotano.com`) && PathPrefix(`/api/v1/ranking`)"
        - "traefik.http.routers.rankingapihttp.middlewares=redirecthttps,rankingapiratelimit"
        - "traefik.http.middlewares.rankingapiratelimit.ratelimit.average=100"
        - "traefik.http.middlewares.rankingapiratelimit.ratelimit.burst=50"
    environment:
      - CONNECTIONSTRINGS__REDIS=redis
      - ALLOWEDHOSTS=minesweeper.rulyotano.com