name: Deploy Minesweeper

on: 
  workflow_dispatch:

env:
  SWARM_FILE_ADDRESS: https://raw.githubusercontent.com/rulyotano/minesweeper/master/src/docker-compose.production.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get swarm file from repo
        run: |
          wget $SWARM_FILE_ADDRESS -o docker-compose.yml
          ssh-keyscan minesweeper.rulyotano.com
      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: stack deploy -c docker-compose.yml minesweeper
  
