name: Deploy Minesweeper

on: 
  workflow_dispatch:

env:
  SWARM_FILE_ADDRESS: https://raw.githubusercontent.com/rulyotano/minesweeper/master/src/docker-compose.production.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ssh connect and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: |
            wget ${{ env.SWARM_FILE_ADDRESS }} -o docker-compose.yml
            docker stack deploy -c docker-compose.yml minesweeper
            rm docker-compose.yml
  
