name: Deploy Minesweeper

on: 
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/base.deploy.yml
    secrets: inherit
    with:
      name: minesweeper
      fileAddress: https://raw.githubusercontent.com/rulyotano/minesweeper/master/src/docker-compose.production.yml
    
