# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Presentation Web Test

on:
  pull_request:
    paths: src/presentation/web
  push:
    branches: [ master ]
    paths: src/presentation/web

jobs:
  build-test-image:    
    name: Build and test image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/presentation/web
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
      - name: Unit Testing in Docker
        run: |
          docker run --rm ${{ github.run_id }}
      
