# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Presentation Web Test

on:
  pull_request:
    branches: 
      - master
    paths:
      - src/presentation/web/**
  push:
    branches: 
      - master
    paths:
      - src/presentation/web/**

jobs:
  build-test-image:    
    name: Build and test image
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          context: src/presentation/web/
      - name: Unit Testing in Docker
        run: docker run --rm ${{ github.run_id }}

  build-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    # if: ${{ github.event_name != 'pull_request' }}
    #needs:
    #  - build-test-image
    permissions:
      pull-requests: write # needed to create and update comments in PRs
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Compile
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: ${{ github.run_id }}
          target: build
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          context: src/presentation/web/
      - name: Copy build directory
        run: |
          docker run -d --name mineswipper-build ${{ github.run_id }} ping localhost
          docker cp mineswipper-build:/app/build ./src/presentation/web/
          docker rm -f mineswipper-build
          ls ./src/presentation/web/build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: rulyotano/minesweeper-presentation-web
          flavor: |
            latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Docker build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          target: prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: src/presentation/web/
          file: '{context}/Dockerfile.prod'
          platforms: linux/amd64,linux/arm64,linux/arm/v7
